Repository codeit-2team/GlobalNomad, pull requests merged in 2025-08, with the labels that each got.

#104 Design/99 체험 등록/수정 페이지 반응형 및 UI 구현 완료
  src/app/(with-header)/myactivity/[id]/components/EditActivityForm.tsx
  src/app/(with-header)/myactivity/components/AddressInput.tsx
  src/app/(with-header)/myactivity/components/CategoryInput.tsx
  src/app/(with-header)/myactivity/components/ImagePreview.tsx
  src/app/(with-header)/myactivity/components/ImageSection.tsx
  src/app/(with-header)/myactivity/components/InfoSection.tsx
  src/app/(with-header)/myactivity/components/MainImageSelect.tsx
  src/app/(with-header)/myactivity/components/ReservationForm.tsx
  src/app/(with-header)/myactivity/components/ScheduleSelect.tsx
  src/app/(with-header)/myactivity/components/ScheduleSelectForm.tsx
  src/app/(with-header)/myactivity/components/SubImageSelect.tsx
  src/app/globals.css
  src/components/Input.tsx
  src/components/Textarea.tsx
  src/types/inputTypes.ts
Labels: 🎨 design, 💻 chore, ✨ Feature, 🔨 Refactor

#108 Chore/107 환경변수 추가
  .github/workflows/deploy.yml
Labels: 💻 chore

#110 Fix/109 빌드 시점에 환경 변수를 주입하여 API 경로 오류 수정
  .github/workflows/deploy.yml
  Dockerfile
Labels: 🐞 bug

#112 Refactor/92 메인페이지 삭제 로직 반영 및 Tanstack Query 도입
  package.json
  pnpm-lock.yaml
  src/app/(with-header)/activities/[id]/hooks/useDeleteActivity.ts
  src/app/(with-header)/components/ExperienceList.tsx
  src/app/(with-header)/components/PopularExperiences.tsx
  src/app/api/experiences/getExperiences.ts
  src/app/api/experiences/getPopularExperiences.ts
Labels: 📬 API, ✨ Feature, 🔨 Refactor

#116 Feat/89 알림 컴포넌트 구현
  src/app/(non-header)/login/components/LoginForm.tsx
  src/app/(non-header)/signup/components/SignupForm.tsx
  src/app/api/my-notifications/[notificationId]/route.ts
  src/app/api/my-notifications/route.ts
  src/components/Header.tsx
  src/components/Loading.tsx
  src/components/Notification/NotificationCard.tsx
  src/components/Notification/NotificationCardList.tsx
  src/components/Notification/NotificationDropdown.tsx
  src/hooks/useDeleteNotification.ts
  src/hooks/useLogout.ts
  src/hooks/useNotification.ts
  src/types/notificationType.ts
  src/utils/relativeTime.ts
Labels: ✨ Feature, 🔨 Refactor

#118 Fix/113 헤더, 푸터, 메인 페이지 이슈 해결
  public/assets/img/main-banner.jpg
  public/assets/svg/github.tsx
  src/app/(with-header)/components/BannerSection.tsx
  src/app/(with-header)/components/BasePage.tsx
  src/app/(with-header)/components/ExperienceList.tsx
  src/app/(with-header)/components/PopularExperiences.tsx
  src/app/(with-header)/components/SearchBar.tsx
  src/app/(with-header)/components/Skeletons/ExperienceCardSkeleton.tsx
  src/app/(with-header)/components/Skeletons/PopularCardSkeleton.tsx
  src/app/(with-header)/page.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/ProfileDropdown.tsx
  src/hooks/useMyPageQueries.ts
  src/middleware.ts
Labels: 🐞 bug, 🎨 design, 💻 chore, 📬 API, ✨ Feature, 🔨 Refactor

#127 Fix/117 QA사항수정 및 리팩토링
  src/app/(with-header)/myactivity/[id]/components/EditActivityForm.tsx
  src/app/(with-header)/myactivity/[id]/hooks/useEditActivityForm.ts
  src/app/(with-header)/myactivity/components/InfoSection.tsx
  src/app/(with-header)/myactivity/components/ReservationForm.tsx
  src/app/(with-header)/myactivity/hooks/useCreateActivityForm.ts
  src/components/Button.tsx
  src/components/FloatingBox/BookingInterface.tsx
  src/components/FloatingBox/hooks/useBookingMutation.ts
  src/hooks/useBookingMutation.ts
  src/stores/Booking/useBookingStore.ts
  src/types/bookingStoreTypes.ts
  src/types/buttonTypes.ts
  src/ui/MobileBookingModal.tsx
  src/ui/TabletBookingModal.tsx
Labels: 🔨 Refactor

#125 Fix/122 회원가입 비밀번호 확인 오류 및 팝업 오류 개선
  src/app/(non-header)/signup/components/SignupForm.tsx
  src/components/Popup.tsx
Labels: 🐞 bug

#124 Feat/123 예약내역, 체험관리 반응형 및 레이아웃 개선
  src/app/(with-header)/mypage/activities/components/ActivityCard.tsx
  src/app/(with-header)/mypage/reservations/components/ReservationCard.tsx
  src/app/(with-header)/mypage/reservations/page.tsx
Labels: ✨ Feature

#129 Feat/126 알림 표시 기능 구현
  src/components/Header.tsx
Labels: ✨ Feature

#142 fix/140 3차 QA수정사항수정
  src/app/(with-header)/activities/[id]/components/ReviewSection.tsx
  src/app/(with-header)/myactivity/[id]/hooks/useEditActivityForm.ts
  src/app/(with-header)/myactivity/components/InfoSection.tsx
  src/components/Button.tsx
  src/components/FloatingBox/BookingButton.tsx
Labels: 🔨 Refactor

#141 Fix/139 3차 QA 수정
  src/app/(with-header)/mypage/dashboard/page.tsx
  src/app/(with-header)/mypage/reservations/page.tsx
  src/components/Dropdown.tsx
  src/hooks/useActivityOptions.ts
  src/hooks/useMyActivitiesQueries.ts
  src/hooks/useReservationQueries.ts
  src/types/dropdownTypes.ts
Labels: 🐞 bug

#147 style: og-image 변경
  public/og-image.png
Labels: 🎨 design

#151 Fix/150 og-image 크기 수정
  public/og-image.png
Labels: 🎨 design

#155 Docs/152 README 작성
  README.md
Labels: 📃 Docs

#157 Fix/156 일정 검증로직 추가
  src/app/(with-header)/myactivity/[id]/hooks/useEditActivityForm.ts
  src/app/(with-header)/myactivity/components/ScheduleSelect.tsx
  src/app/(with-header)/myactivity/components/ScheduleSelectForm.tsx
  src/app/(with-header)/myactivity/utils/dateValidatoin.ts
Labels: 🔨 Refactor
