Repository codeit-2team/GlobalNomad, pull requests merged in 2025-07, with the labels that each got.

#6 Feat/3 Input 공통 컴포넌트
  src/app/layout.tsx
  src/assets/icon/closeEye.tsx
  src/assets/icon/openEye.tsx
  src/components/Input.tsx
Labels: ✨ Feature

#5 Feat/2 모달 공통 컴포넌트
  src/app/assets/icons/close.tsx
  src/app/layout.tsx
  src/components/input/Input.tsx
  src/components/input/types.ts
  src/components/modal/Example/TestModal.tsx
  src/components/modal/Example/TestModalButton.tsx
  src/components/modal/Example/UncontrolledModal.tsx
  src/components/modal/Example/readme
  src/components/modal/Modal.tsx
  src/components/modal/ModalClose.tsx
  src/components/modal/ModalContent.tsx
  src/components/modal/ModalContext.tsx
  src/components/modal/ModalFooter.tsx
  src/components/modal/ModalHeader.tsx
  src/components/modal/ModalItem.tsx
  src/components/modal/ModalTitle.tsx
  src/components/modal/ModalTrigger.tsx
  src/components/modal/index.ts
  src/components/modal/types.ts
Labels: ✨ Feature

#30 Setting/28 절대 경로 추가
  src/components/button/Button.tsx
  src/components/footer/Footer.tsx
  src/components/header/Header.tsx
  src/components/input/Input.tsx
  src/components/modal/Example/TestModal.tsx
  src/components/modal/ModalClose.tsx
  src/components/modal/ModalContent.tsx
  src/components/modal/ModalFooter.tsx
  src/components/modal/ModalHeader.tsx
  src/components/modal/ModalItem.tsx
  src/components/modal/ModalTitle.tsx
  src/lib/utils.ts
  tsconfig.json
Labels: ⚙ setting

#35 refactor/32 대소문자/폴더구조/타입분리등 컨벤션수정
  src/components/Modal/Close.tsx
  src/components/Modal/Content.tsx
  src/components/Modal/Example/TestModal.tsx
  src/components/Modal/Example/TestModalButton.tsx
  src/components/Modal/Example/UncontrolledModal.tsx
  src/components/Modal/Example/readme
  src/components/Modal/Footer.tsx
  src/components/Modal/Header.tsx
  src/components/Modal/Item.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/Title.tsx
  src/components/Modal/Trigger.tsx
  src/components/Modal/index.ts
  src/components/modal/index.ts
  src/contexts/ModalContext.tsx
  src/types/modalTypes.ts
  tsconfig.json
Labels: 🔨 Refactor

#24 Feat/14 공통 Pagination 컴포넌트 구현
  src/app/assets/icons/left-arrow.tsx
  src/app/assets/icons/right-arrow.tsx
  src/components/pagination/Pagination.tsx
  src/components/pagination/example/Pagination.tsx
  src/components/pagination/example/readme
  src/components/pagination/type.ts
Labels: ✨ Feature

#19 Feat/13 popup 컴포넌트 구현
  src/assets/icon/check.tsx
  src/components/popup/Popup.tsx
  src/components/popup/types.ts
  src/hooks/useOutsideClick.ts
Labels: ✨ Feature

#39 refactor/38 컨벤션 수정사항 적용/layout.tsx에 modal-root추가
  src/app/layout.tsx
  src/components/DatePicker/CalendarBody.tsx
  src/components/DatePicker/CalendarHeader.tsx
  src/components/DatePicker/DatePicker.tsx
  src/components/FloatingBox/BookingButton.tsx
  src/components/FloatingBox/BookingInterface.tsx
  src/components/FloatingBox/ParticipantSelector.tsx
  src/components/FloatingBox/PriceDisplay.tsx
  src/components/FloatingBox/TabletPopup.tsx
  src/components/FloatingBox/TimeSelector.tsx
  src/components/FloatingBox/TotalPriceDisplay.tsx
  src/components/floating-box/Calendar.tsx
  src/components/floating-box/styles/DatePickerStyles.tsx
  src/hooks/useDeviceSize.ts
  src/stores/Booking/useBookingStore.ts
  src/types/bookingStoreTypes.ts
  src/types/datePickerTypes.ts
  src/ui/BookingModal.tsx
  src/ui/MobileBookingModal.tsx
  src/ui/TabletBookingModal.tsx
Labels: 🔨 Refactor

#44 refactor/31 헤더, 푸터, 페이지네이션 관련 리팩토링 및 타입 오류 관련 파일 삭제
  public/assets/svg/bell.tsx
  public/assets/svg/facebook.tsx
  public/assets/svg/instagram.tsx
  public/assets/svg/left-arrow.tsx
  public/assets/svg/logo.tsx
  public/assets/svg/right-arrow.tsx
  public/assets/svg/twitter.tsx
  public/assets/svg/youtube.tsx
  src/app/layout.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/Pagination.tsx
  src/components/pagination/example/Pagination.tsx
  src/components/pagination/example/readme
  src/types/paginationTypes.ts
Labels: 🐞 bug, 🔨 Refactor

#42 feat/19 아바타 컴포넌트 구현
  public/assets/svg/profile-default.svg
  src/components/Avatar.tsx
  src/constants/AvatarConstants.ts
  src/types/AvatarType.ts
Labels: ✨ Feature

#53 Fix/50 헤더 컴포넌트 빌드 에러 수정
  src/components/Header.tsx
Labels: 🐞 bug

#51 feat/48 레이아웃분리/상세페이지 타이틀,이미지그리드 컴포넌트 구현/배포에러잡히는 부분 수정
  public/assets/svg/dropdown.tsx
  public/test/image1.png
  public/test/image2.png
  public/test/image3.png
  public/test/image4.png
  public/test/image5.png
  src/app/(non-header)/layout.tsx
  src/app/(with-header)/activities/[activitiesId]/components/ImageGrid.tsx
  src/app/(with-header)/activities/[activitiesId]/components/Title.tsx
  src/app/(with-header)/activities/[activitiesId]/mock/mock.ts
  src/app/(with-header)/activities/[activitiesId]/page.tsx
  src/app/(with-header)/layout.tsx
  src/app/layout.tsx
  src/components/Avatar.tsx
  src/components/FloatingBox/BookingButton.tsx
  src/lib/queryProvider.tsx
  src/ui/MobileBookingModal.tsx
Labels: ✨ Feature

#36 Feature/16 OCI 서버 배포 및 Docker 기반 CI/CD 파이프라인 구축
  .dockerignore
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  Dockerfile
  docker-compose.yml
  init-letsencrypt.sh
  next.config.ts
  nginx/conf.d/default.conf
  nginx/nginx.conf
  package.json
  pnpm-lock.yaml
Labels: 🌏 Deploy, 💻 chore

#63 Fix/62 metadata-action으로 CD 배포 실패 오류 수정
  .github/workflows/deploy.yml
Labels: 🐞 bug, 🌏 Deploy

#72 Feat/45-2 메인페이지 인기 체험 섹션 UI 구현
  src/app/(with-header)/components/BannerSection.tsx
  src/app/(with-header)/components/ExperienceCard.tsx
  src/app/(with-header)/components/PopularExperiences.tsx
  src/app/(with-header)/components/SearchBar.tsx
  src/app/(with-header)/page.tsx
  src/app/globals.css
Labels: 🎨 design, ✨ Feature

#76 Feat/61 마이페이지 구현(UI 및 API 연동)
  next.config.ts
  public/assets/svg/my-activities-dashboard.tsx
  public/assets/svg/my-activities.tsx
  public/assets/svg/my-reservation.tsx
  public/assets/svg/my-user.tsx
  public/assets/svg/pen.tsx
  public/assets/svg/profile-default.tsx
  src/apis/mypage.ts
  src/app/(with-header)/mypage/activities/page.tsx
  src/app/(with-header)/mypage/components/ProfileImage.tsx
  src/app/(with-header)/mypage/components/ProfileNavigation.tsx
  src/app/(with-header)/mypage/components/index.ts
  src/app/(with-header)/mypage/dashboard/page.tsx
  src/app/(with-header)/mypage/layout.tsx
  src/app/(with-header)/mypage/page.tsx
  src/app/(with-header)/mypage/profile/page.tsx
  src/app/(with-header)/mypage/reservations/page.tsx
  src/app/api/users/me/image/route.ts
  src/app/api/users/me/route.ts
  src/hooks/useDebounce.ts
  src/hooks/useMyPageQueries.ts
  src/hooks/useProfileImageUpload.ts
  src/hooks/useResponsiveRouting.ts
  src/stores/MyPage/useMyPageStore.ts
  src/types/mypageTypes.ts
Labels: ✨ Feature

#82 Feat/77 체험등록 페이지 api 연결
  src/app/(with-header)/myactivity/components/ImagePreview.tsx
  src/app/(with-header)/myactivity/components/ReservationForm.tsx
  src/app/(with-header)/myactivity/utils/uploadImage.ts
  src/app/api/addActivity/route.ts
  src/app/api/image/route.ts
Labels: ✨ Feature

#85 Fix/75 빌드 오류 수정 및 알림창 변경
  next.config.ts
  src/app/(non-header)/oauth/kakao/components/KakaoLoading.tsx
  src/app/(non-header)/oauth/kakao/sign-in/kakaoSigninCallbackPage.tsx
  src/app/(non-header)/oauth/kakao/sign-in/page.tsx
  src/app/(non-header)/oauth/kakao/sign-up/kakaoSignupCallbackPage.tsx
  src/app/(non-header)/oauth/kakao/sign-up/page.tsx
  src/app/globals.css
  src/components/Loading.tsx
  src/middleware.ts
  src/types/popupTypes.ts
Labels: 🐞 bug, ✨ Feature
